Terminalpython and outputsaving
ESA-Datalabs/datalabtools pull request #7
Opened 2024-02-13 12:25 UTC by Lasloruhberg

Just two short help pages about common problems. Saving cell output while not actively being connected to the server is quite useful and I believe not directly logically why this does not work as expected.
The second part about the python alias is not really necessary, but perhaps it saves someone a few minutes.

2024-02-14 10:23 UTC, gomezzz requested changes
Thanks @Lasloruhberg !

Some minor suggestions to make it a bit more generic

2024-02-14 10:23 UTC, gomezzz commented on docs/Using python in the terminal.md
> +alias python3.11='/opt/miniconda/bin'
```suggestion
alias python='/opt/miniconda/bin'
```

may be simpler?

2024-02-14 10:23 UTC, gomezzz commented on docs/Using python in the terminal.md
> +then python can be launched from inside the terminal by calling the alias.
```suggestion
then calling `python` inside the terminal will launch that version.
```

2024-02-14 10:23 UTC, gomezzz commented on docs/Using python in the terminal.md
> +os.path.dirname(sys.executable)
```suggestion
# this will display the the path to the Python binary used in Jupyter
os.path.dirname(sys.executable)
```

2024-02-14 10:23 UTC, gomezzz commented on docs/Using python in the terminal.md
> +The python installation can be found from a notebook via
Would make more generic
```suggestion
In some cases the standard jupyterlab environment may use a different Python interpreter than the system's default.
The python installation used by Jupyter can be found from a notebook via
```

2024-02-14 10:25 UTC, gomezzz commented on docs/Using python in the terminal.md
> +```bash
```suggestion
```py
```

2024-02-14 10:26 UTC, gomezzz commented on docs/Saving notebook output when tab is closed.md
> +```bash
```py
```bash
```

2024-02-14 15:47 UTC, Lasloruhberg commented on docs/Using python in the terminal.md
> +alias python3.11='/opt/miniconda/bin'
Yeah I though about it, but python already refers to python2.7 and python3 to 3.6.5 I was unsureif verwriting those could possibly break something. This would be the safer route (applicable in the case of a more general datalabs where something might refer to that python)

2024-02-14 16:04 UTC, gomezzz commented on docs/Using python in the terminal.md
> +alias python3.11='/opt/miniconda/bin'
the alias is only applied during the current terminal session and user, I think. So shouldn't be too risky

2024-02-29 11:58 UTC, gomezzz approved these changes
👍 Thanks!

2024-02-29 11:58 UTC, merged